-- SQL query to create the fg_delivery_schedule table for Supabase

-- 1. Drop the old table if it exists and you want a fresh start
-- DROP TABLE IF EXISTS public.fg_delivery_schedule;

-- 2. Create the new table with the correct columns
CREATE TABLE public.fg_delivery_schedule (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  sales_no text,
  sales_item text,
  customer_name text,
  print_design text,
  rdd date,
  gross_weight numeric,
  order_qty integer,
  schedule_date date NOT NULL,
  plant text NOT NULL,
  user_name text,
  CONSTRAINT fg_delivery_schedule_pkey PRIMARY KEY (id)
);

-- 3. Enable Row Level Security (RLS) for the table
-- This is a Supabase best practice to ensure your data is secure.
ALTER TABLE public.fg_delivery_schedule ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to control access
-- This policy allows any authenticated user to view all delivery schedules.
CREATE POLICY "Allow authenticated users to view schedules"
ON public.fg_delivery_schedule
FOR SELECT
TO authenticated
USING (true);

-- This policy allows any authenticated user to insert new delivery schedules.
CREATE POLICY "Allow authenticated users to insert schedules"
ON public.fg_delivery_schedule
FOR INSERT
TO authenticated
WITH CHECK (true);
