-- SQL query to create the fg_stock_movements table for Supabase

-- 1. Drop the old table if it exists and you want a fresh start
DROP TABLE IF EXISTS public.fg_stock_movements;

-- 2. Create the new table with the correct columns
CREATE TABLE public.fg_stock_movements (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  lmg_number text NOT NULL,
  plant text, -- Added to specify which plant the movement belongs to
  movement_type text,
  so_number text,
  so_item text,
  customer_name text, -- Added to store customer name
  print_design text, -- Added to store print design
  initial_loc text,
  destination_loc text,
  timestamp timestamptz DEFAULT now(),
  quantity integer,
  user_id text,
  delivery_schedule_id bigint,
  truck_no text,
  CONSTRAINT fg_stock_movements_pkey PRIMARY KEY (id)
);

-- 3. Enable Row Level Security (RLS) for the table
ALTER TABLE public.fg_stock_movements ENABLE ROW LEVEL SECURITY;

-- 4. Create policies for access control
-- Note: Policies might need to be adjusted based on your security requirements.
CREATE POLICY "Allow authenticated users to view movements" ON public.fg_stock_movements FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated users to insert movements" ON public.fg_stock_movements FOR INSERT TO authenticated WITH CHECK (true);
